# Generated by Django 5.1 on 2024-09-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemNotaVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_item', models.IntegerField()),
            ],
            options={
                'db_table': 'item_nota_venda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NotaVenda',
            fields=[
                ('id_nota_venda', models.AutoField(primary_key=True, serialize=False)),
                ('valor_total', models.FloatField()),
                ('data_nota_venda', models.DateField()),
                ('desc_venda', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'nota_venda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPagamento',
            fields=[
                ('id_tipo_pagamento', models.AutoField(primary_key=True, serialize=False)),
                ('desc_tipo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipo_pagamento',
                'managed': False,
            },
        ),
    ]
