# Generated by Django 5.1.2 on 2024-10-08 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emitente',
            fields=[
                ('id_emitente', models.AutoField(primary_key=True, serialize=False)),
                ('cnpj', models.CharField(max_length=30, unique=True)),
                ('codigo_de_regime_tributario', models.IntegerField()),
                ('inscricao_estadual', models.CharField(blank=True, max_length=30, null=True)),
                ('inscricao_municipal', models.CharField(blank=True, max_length=30, null=True)),
                ('cnae_fiscal', models.CharField(blank=True, max_length=40, null=True)),
                ('endereco_logradouro', models.CharField(max_length=100)),
                ('endereco_numero', models.CharField(max_length=20)),
                ('endereco_bairro', models.IntegerField()),
                ('endereco_municipio', models.CharField(max_length=100)),
                ('endereco_uf', models.CharField(max_length=20)),
                ('endereco_cep', models.CharField(max_length=30)),
                ('endereco_pais', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'emitente',
                'managed': False,
            },
        ),
    ]
