# Generated by Django 5.1.2 on 2024-10-08 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemNFe',
        ),
        migrations.DeleteModel(
            name='NFe',
        ),
    ]
