# Generated by Django 5.1 on 2024-09-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id_bairro', models.AutoField(primary_key=True, serialize=False)),
                ('nome_bairro', models.CharField(max_length=100)),
                ('frete_bairro', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bairro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome_cliente', models.CharField(max_length=100)),
                ('telefone_cliente', models.CharField(max_length=100)),
                ('rua_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_cliente', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
    ]
