# Generated by Django 5.1 on 2024-08-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome_produto', models.CharField(max_length=100)),
                ('desc_produto', models.CharField(blank=True, max_length=100, null=True)),
                ('quantidade_disponivel', models.IntegerField(blank=True, null=True)),
                ('preco_produto', models.FloatField(blank=True, null=True)),
                ('nivel_abastecimento', models.IntegerField(blank=True, null=True)),
                ('imagem_produto', models.CharField(blank=True, max_length=100, null=True)),
                ('data_ultima_reposicao', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'produto',
                'managed': False,
            },
        ),
    ]
